name: Teste workflow

on: 
  workflow_dispatch:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: seila
        run: echo ${{ github.ref }}
      
      - name: test branch name
        if: contains('refs/heads/master', github.ref)
        run: |
          echo "::error::Not master branch"
          exit 1
