name: Teste workflow

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: seila
        run: echo ${{ github.ref }}
      
      - name: test branch name
        if: ${{ github.ref }} != refs/heads/master
        run: |
          echo "::error::Not master branch"
          exit 1
